### ISSUE TITLE
When running the script ./SemKGE_creation.sh en , an error occurred

### ISSUE THREAD

**Issue by DonnieZhang586** [dice-group/KG-NMT#1]
if [ ! -f "$SOURCEDIR/all_"$SOURCEDIR".txt" ]; then
	sed -i '' -e '/http/!d' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/<http:\/\/dbpedia.org\/resource\//dbr_/g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/<http:\/\/de.dbpedia.org\/resource\//dbr_de_/g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/<http:\/\/www.w3.org\/2000\/01\/rdf-schema#/rdfs_/g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/<http:\/\/xmlns.com\/foaf\/0.1\//foaf_/g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/<http:\/\/schema.org\//schema_/g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/<http:\/\/purl.org\/dc\/terms/dc_/g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/<http:\/\/purl.org\/dc\/elements\/1.1\//dc_/g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/<http:\/\/www.w3.org\/2004\/02\/skos\/core#/skos_/g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/<http:\/\/dbpedia.org\/ontology\//dbo_/g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/<http:\/\/de.dbpedia.org\/property\//dbp_de_/g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/<http:\/\/dbpedia.org\/datatype\//dbt_/g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/<http:\/\/www.w3.org\/2002\/07\/owl#/owl_/g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/<http:\/\/www.w3.org\/1999\/02\/22-rdf-syntax-ns#/rdf_/g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/@en//g'  $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/@de//g'  $SOURCEDIR/*_lc.txt
	sed -i '' -e '/ontologydesignpatterns/d'  $SOURCEDIR/*_lc.txt
	sed -i '' -e '/foaf_homepage/d'  $SOURCEDIR/*_lc.txt
	sed -i '' -e '/wikidata_/d'  $SOURCEDIR/*_lc.txt
	sed -i '' -e '/schema_/d'  $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/^^rdf_langString//g'  $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/\.//g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/>//g' $SOURCEDIR/*_lc.txt
	sed -i '' -e 's/"//g' $SOURCEDIR/*_lc.txt
	sed -i '' -e '/%3f/d' $SOURCEDIR/*_lc.txt
	sed -i '' -e '/%/d' $SOURCEDIR/*_lc.txt
	awk '{print $1, $2, $3;print $3, $2, $1}' < $SOURCEDIR/instance_types_"$1"_lc.txt > $SOURCEDIR/instance_types_"$1"_new_lc.txt
	awk '{print $1, $2, $3;print $3, $2, $1}' < $SOURCEDIR/mappingbased_objects_"$1"_lc.txt > $SOURCEDIR/$SOURCEDIR/mappingbased_objects_"$1"_new_lc.txt 
	awk '{printf "__label__"$1" "; for(i=2;i<=NF;i++){printf $i" "}print ""}' < $SOURCEDIR/labels_"$1"_lc.txt > $SOURCEDIR/labels_"$1"_new_lc.txt
	rm -rf $SOURCEDIR/labels_"$1"_lc.txt
	rm -rf $SOURCEDIR/instance_types_"$1"_lc.txt
	rm -rf $SOURCEDIR/mappingbased_objects_"$1"_lc.txt
	awk 'FNR==1{print ""}{print}' $SOURCEDIR/*_lc.txt > $SOURCEDIR/all_"$1".txt
fi

sed: can't read : No such file or directory
sed: can't read : No such file or directory
。。。。。。。。

please help me，thank you so much

**Comment by DiegoMoussallem** [comment]
Hi, it depends on the operation system, but actually these messages do not affect your generated file.

**Comment by leileilin** [comment]
> if [ ! -f "$SOURCEDIR/all_"$SOURCEDIR".txt" ]; then sed -i '' -e '/http/!d' $SOURCEDIR/__lc.txt sed -i '' -e 's/<http://dbpedia.org/resource//dbr_/g' $SOURCEDIR/__lc.txt sed -i '' -e 's/<http://de.dbpedia.org/resource//dbr_de_/g' $SOURCEDIR/__lc.txt sed -i '' -e 's/<http://www.w3.org/2000/01/rdf-schema#/rdfs_/g' $SOURCEDIR/__lc.txt sed -i '' -e 's/<http://xmlns.com/foaf/0.1//foaf_/g' $SOURCEDIR/__lc.txt sed -i '' -e 's/<http://schema.org//schema_/g' $SOURCEDIR/__lc.txt sed -i '' -e 's/<http://purl.org/dc/terms/dc_/g' $SOURCEDIR/__lc.txt sed -i '' -e 's/<http://purl.org/dc/elements/1.1//dc_/g' $SOURCEDIR/__lc.txt sed -i '' -e 's/<http://www.w3.org/2004/02/skos/core#/skos_/g' $SOURCEDIR/__lc.txt sed -i '' -e 's/<http://dbpedia.org/ontology//dbo_/g' $SOURCEDIR/__lc.txt sed -i '' -e 's/<http://de.dbpedia.org/property//dbp_de_/g' $SOURCEDIR/__lc.txt sed -i '' -e 's/<http://dbpedia.org/datatype//dbt_/g' $SOURCEDIR/__lc.txt sed -i '' -e 's/<http://www.w3.org/2002/07/owl#/owl_/g' $SOURCEDIR/__lc.txt sed -i '' -e 's/<http://www.w3.org/1999/02/22-rdf-syntax-ns#/rdf_/g' $SOURCEDIR/__lc.txt sed -i '' -e 's/@en//g' $SOURCEDIR/__lc.txt sed -i '' -e 's/@de//g' $SOURCEDIR/__lc.txt sed -i '' -e '/ontologydesignpatterns/d' $SOURCEDIR/__lc.txt sed -i '' -e '/foaf_homepage/d' $SOURCEDIR/__lc.txt sed -i '' -e '/wikidata_/d' $SOURCEDIR/__lc.txt sed -i '' -e '/schema_/d' $SOURCEDIR/__lc.txt sed -i '' -e 's/^^rdf_langString//g' $SOURCEDIR/__lc.txt sed -i '' -e 's/.//g' $SOURCEDIR/__lc.txt sed -i '' -e 's/>//g' $SOURCEDIR/__lc.txt sed -i '' -e 's/"//g' $SOURCEDIR/__lc.txt sed -i '' -e '/%3f/d' $SOURCEDIR/__lc.txt sed -i '' -e '/%/d' $SOURCEDIR/__lc.txt awk '{print $1, $2, $3;print $3, $2, $1}' < $SOURCEDIR/instance_types_"$1"_lc.txt > $SOURCEDIR/instance_types_"$1"_new_lc.txt awk '{print $1, $2, $3;print $3, $2, $1}' < $SOURCEDIR/mappingbased_objects_"$1"_lc.txt > $SOURCEDIR/$SOURCEDIR/mappingbased_objects_"$1"_new_lc.txt awk '{printf "**label**"$1" "; for(i=2;i<=NF;i++){printf $i" "}print ""}' < $SOURCEDIR/labels_"$1"_lc.txt > $SOURCEDIR/labels_"$1"_new_lc.txt rm -rf $SOURCEDIR/labels_"$1"_lc.txt rm -rf $SOURCEDIR/instance_types_"$1"_lc.txt rm -rf $SOURCEDIR/mappingbased_objects_"$1"_lc.txt awk 'FNR==1{print ""}{print}' $SOURCEDIR/*_lc.txt > $SOURCEDIR/all_"$1".txt fi
> 
> sed: can't read : No such file or directory sed: can't read : No such file or directory 。。。。。。。。
> 
> please help me，thank you so much

delete '' behind -i  in that command, then it is going well.
